### ISSUE TITLE
Linter fails a PR with no file changes when adding new rules

### ISSUE THREAD

**Issue by pdewouters** [humanmade/linter-bot#111] opened 2019-12-10 10:14 UTC
Given a pull request that adds `eslint` rules for core rules or a ruleset included in our eslint config, and given the existing code fails these rules, even if no changes to these files are in the pull request, the linter ot fails the pull request. 
This makes it impossible to add new rules for linting code only added to the codebase after the rules are added.
Let's say I want to use `lint-staged` locally so that I only apply the new linting config to changed files, then if this code is validated locally, it should be possible to pass the linter bot checks.

**Comment by mikeselander** [comment] 2020-05-29 15:59
This is a duplicate of #78 and is a pretty consistent complaint across our projects.

**Closed by mikeselander** 2020-05-29 15:59 UTC
